services:
  api:
    volumes:
      - ./input_samples:/app/input_samples:ro
      - ./extensions/brain:/app/extensions/brain:rw
      - ./prepared_docs:/app/prepared_docs:rw
      - api_data:/app/data

  api_dev_off:
    volumes:
      - ./data:/app/data
