from enum import Enum


class KernelErrorCode(str, Enum):
    # Core command errors
    KERNEL_UNKNOWN_COMMAND = "KERNEL_UNKNOWN_COMMAND"
    KERNEL_SPEC_MISMATCH = "KERNEL_SPEC_MISMATCH"
    KERNEL_PARAMS_MISMATCH = "KERNEL_PARAMS_MISMATCH"
    KERNEL_EXECUTION_CLASS_FORBIDDEN = "KERNEL_EXECUTION_CLASS_FORBIDDEN"

    # Confirmation errors
    CONFIRMATION_FAILED = "CONFIRMATION_FAILED"

    # Generic
    KERNEL_VALIDATION_ERROR = "KERNEL_VALIDATION_ERROR"
    READ_ONLY_EXECUTION_ERROR = "READ_ONLY_EXECUTION_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"

    # Client ID 
    MISSING_CLIENT_ID = "MISSING_CLIENT_ID"

    # Rate limiting
    RATE_LIMITED = "RATE_LIMITED"
    RATE_LIMITER_FAILURE = "RATE_LIMITER_FAILURE"
